config/routes.rb
Icare::Application.routes.draw do
  resources :authentications
  authenticated :user do
    root :to => 'sites#index'
  end
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  match 'sites/return_to_referrer' => 'sites#return_to_referrer'
  match 'sites/post_to_wall' => 'sites#post_to_wall'
  match 'sites/get_count/:id' => 'sites#get_count'
  match 'api' => 'sites#api'
  resources :sites
  match 'imp_sites/:owner/:site_id' => 'sites#impress'
  devise_for :users, :controllers => {:registrations => "registrations"}
   
      match '/auth/:provider/callback' => 'authentications#create'

end

app/models/site.rb
class Site
  include Mongoid::Document
  include Mongo::Voteable
  include Mongoid::Taggable
  
  field :name, type: String
  field :url, type: String
  field :description, type: String
  field :supporters, type: Array
  field :tags, type: Array
  field :count, type: Integer 
  belongs_to :user
  embeds_many :supports
  attr_accessible :name, :url, :description, :supporters, :tags, :count

  
  tags_separator ' '
  
  
  voteable self, :up => +1, :down => -1
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!, :except => ['impress', 'post_to_wall', 'get_count']
  # GET /sites
  # GET /sites.json
  def index
    @sites = current_user.sites.all
    @site = current_user.sites.new
    
  
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites, :only => [:_id, :name, :url, :description, :supporters, :tags, :count], :methods => ['votes_count'] }
      #format.json { render json: @sites }
    end
  end
  
  
  def post_to_wall
    session[:icare_referrer] = request.env['HTTP_REFERER']
    respond_to do |format|
      format.html 
      format.json { render json: @sites }
    end
  end
  
  def get_count
    @count = Site.find(params[:id]).votes_count
    
    respond_to do |format|
      format.html { render :layout => false }
    end
  end
  
  
  def return_to_referrer
 
    if session[:icare_referrer].nil? || session[:icare_referrer] == '' then
       redirect_to '/'
    else
       redirect_to session[:icare_referrer].to_s
    end
  end
  
  # GET /sites/1.json
  def impress
      @user = User.find(params[:owner])
      @site = @user.sites.find(params[:site_id]) # :owner = user's id
 
=begin    
    if not current_user.voted?(@site)
       current_user.vote(@site, :up)
              
      @support = @site.supports.new
      
      @support.ip_address = request.env['REMOTE_ADDR'] if request.env['REMOTE_ADDR'].present?
      @support.save
    end    
=end   
       
       @site.votes['count'] += 1
       @site.save
       @support = @site.supports.new
      
      @support.ip_address = request.env['REMOTE_ADDR'] if request.env['REMOTE_ADDR'].present?
      @support.save
        
  
  
    respond_to do |format|
      #format.html # show.html.erb
     # format.json { render json: @site }
      format.js { render :nothing => true }
    end
  end


  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = current_user.sites.find(params[:id])
    @vote_count = @site.votes_count
    
    
    respond_to do |format|
      format.html { render :layout => false   } # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = current_user.sites.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = current_user.sites.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
  #  @site = params[:site]
  #  @site['tags'] = []
  #  @site['tags'] = params[:site][:tags].split(' ')
    @site = current_user.sites.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to sites_url, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = current_user.sites.find(params[:id])
    
   # @site_temp['tags'] = []
   # @site_updated['tags'] = params[:site][:tags].split(' ')
    
    
    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to sites_url }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = current_user.sites.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
<div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
<div class="field">
    <%= f.label :tags %><br />
    <%= f.text_area :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/api.html.erb
<div id="wrapper">
  <div id="topbar">
<img src="/assets/I_CARE_Logo.png" id="icare_logo"/>
      <span id="header_email"><span id="account_header">Account: </span><%= current_user.email %></span>
      <%= link_to image_tag('/assets/LogOut_BTN.png', :border => 0), destroy_user_session_path, :method => :delete, :id => 'signout_link' %>
      
  </div>

  <div id="manager_main_area">
    <div id="instructions">
      <div><h1 style="margin-left: 18px;">API Documentation</h1></div>
	<br/><br/><br/>
	<div id="manager_instructions">	

	  I Care users can also access the site via our API.  <br/><br/>
	  
	  
	  <% if user_signed_in? %>
	    <b>Your user authentication token</b>: <%= current_user.authentication_token %><br/>
	  <% else %>
	    <%= link_to 'Create an account first', :root %>
	  <% end %>
	</div>
      
    </div>
    <table class="api_table">
      <tr>
	<th>Retrieve a list of your topics</th>
	
	<th></th>
      </tr>

  
      <tr class="showcode_row">
	<td colspan="2" >
	   <b>GET</b> http://<%= request.host_with_port %>/sites.json?auth_token=<%= current_user.authentication_token %>
	</td>
      </tr>
	
    
      <tr id="new_topic_row">
	<td>
	   
		<div class="manager_caretopic_left" id="new_caretopic">
		  
				    
		</div>
		<div class="manager_caretopic_right">
		</div>
	  
	</td>
	
	<td class="clicks_to_date_column"></td>
      </tr>
      <tr id="last_row">
	  <td><b>EXAMPLE REQUEST:</b><br/> <code class="prettyprint lang-js">curl -i -H 'Accept: application/json' -X GET http://<%= request.host_with_port %>/sites.json?auth_token=<%= current_user.authentication_token %>
		  </code><br/><br/>
	      <b>EXAMPLE RESPONSE:</b><br/> <code class="prettyprint lang-js">[
	  {"_id":"4f73e3338520025ac5000099","description":"this is my description","name":"this is my topic name","tags":"tag1 tag2 tag3","url":"www.example-url-1.com","votes_count":5},{"_id":"4f73e3338520025ac5000014","description":"this is my second description","name":"this is my second topic name","tags":"tag1 tag2","url":"www.example-url-2.com","votes_count":15}]</code>
	  </td>
      </tr>
    </table>

    <br />
      <table class="api_table">
      <tr>
	<th>Retrieve a specific topic</th>
	
	<th></th>
      </tr>

  
      <tr class="showcode_row">
	<td colspan="2" >
	   <b>GET</b> http://<%= request.host_with_port %>/sites/<b>topic_id</b>?auth_token=<%= current_user.authentication_token %>
	</td>
      </tr>
	
    
      <tr id="new_topic_row">
	<td>
	   
		<div class="manager_caretopic_left" id="new_caretopic">
		 	      
				    
		</div>
		<div class="manager_caretopic_right">
		</div>
	  
	</td>
	
	<td class="clicks_to_date_column"></td>
      </tr>
      <tr id="last_row">
	  <td><b>EXAMPLE REQUEST:</b><br/> <code class="prettyprint lang-js">curl -i -H 'Accept: application/json' -X GET http://<%= request.host_with_port %>/sites/4f73e3338520025ac5000099.json?auth_token=<%= current_user.authentication_token %>
		  </code><br/><br/>
	      <b>EXAMPLE RESPONSE:</b><br/> <code class="prettyprint lang-js">
	  {"_id":"4f73e3338520025ac5000099","description":"this is my description","name":"this is my topic name","tags":"tag1 tag2 tag3","url":"www.example-url-1.com","votes_count":5}</code>
	
	  </td>
      </tr>
    </table>
    <br/>
    <table class="api_table">
      <tr>
	<th>Update a topic</th>
	
	<th></th>
      </tr>

  
      <tr class="showcode_row">
	<td colspan="2" >
	   <b>PUT</b> http://<%= request.host_with_port %>/sites/<b>topic_id</b>.json?auth_token=<%= current_user.authentication_token %>
	</td>
      </tr>
	
    
      <tr id="new_topic_row">
	<td>
	   
		<div class="manager_caretopic_left" id="new_caretopic">
		 	    
		</div>
		<div class="manager_caretopic_right">
		</div>
	  
	</td>
	
	<td class="clicks_to_date_column"></td>
      </tr>
      <tr id="last_row">
	  <td><b>REQUEST BODY:</b><br/><code   class="prettyprint lang-js">
		site[<b>fieldname</b>]=<b>value for field</b> 
 			 </code>
	      <br/><br/>
	      <b>EXAMPLE:</b> changing name of topic with id 4f73e3338520025ac5000099 to 'Third World Countries'<br/><code   class="prettyprint lang-js">
		curl -i -H 'Accept: application/json'   -X PUT -d 'site[name]=Third World Countries' http://<%= request.host_with_port %>/sites/4f73e3338520025ac5000099.json?auth_token=<%= current_user.authentication_token %>
 			 </code>
	  </td>
      </tr>
    </table>

    <br/>

     <table class="api_table">
      <tr>
	<th>Delete a topic</th>
	
	<th></th>
      </tr>

  
      <tr class="showcode_row">
	<td colspan="2" >
	   <b>DELETE</b> http://<%= request.host_with_port %>/sites/<b>topic_id</b>.json?auth_token=<%= current_user.authentication_token %>
	</td>
      </tr>
	
    
      <tr id="new_topic_row">
	<td>
	   
		<div class="manager_caretopic_left" id="new_caretopic">
	      
				    
		</div>
		<div class="manager_caretopic_right">
		</div>
	  
	</td>
	
	<td class="clicks_to_date_column"></td>
      </tr>
      <tr id="last_row">
	  <td>
	      <b>EXAMPLE:</b> Delete topic with ID 4f73e3338520025ac5000099 <br/><code   class="prettyprint lang-js">
		curl -i -H 'Accept: application/json'   -X DELETE http://<%= request.host_with_port %>/sites/4f73e3338520025ac5000099.json?auth_token=<%= current_user.authentication_token %>
 			 </code>
	  </td>
      </tr>
    </table>

    <br/>

    <table class="api_table">
      <tr>
	<th>Create a topic</th>
	
	<th></th>
      </tr>

  
      <tr class="showcode_row">
	<td colspan="2" >
	   <b>POST</b> http://<%= request.host_with_port %>/sites.json?auth_token=<%= current_user.authentication_token %>
	</td>
      </tr>
	
    
      <tr id="new_topic_row">
	<td>
	   
		<div class="manager_caretopic_left" id="new_caretopic">
		 	      
				    
		</div>
		<div class="manager_caretopic_right">
		</div>
	  
	</td>
	
	<td class="clicks_to_date_column"></td>
      </tr>
      <tr id="last_row">
	  <td><b>REQUEST BODY:</b><br/><code   class="prettyprint lang-js">
		site[<b>fieldname</b>]=<b>value for field</b> 
 			 </code>
	      <br/><br/>
	      <b>EXAMPLE:</b> Creating a new topic, 'Third World Countries'<br/><code   class="prettyprint lang-js">
		curl -i -H 'Accept: application/json'   -X POST -d 'site[name]=Third World Countries' -d 'site[tags]=poverty countries africa thirdworld global' -d 'site[description]=These are the developing and technologically less advanced nations of Asia, Africa, Oceania, and Latin America' http://<%= request.host_with_port %>/sites.json?auth_token=<%= current_user.authentication_token %>
 			 </code>	
	  
	  </td>
      </tr>
    </table>
  </div>

<br/>
    
  </div>

 

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/get_count.html.erb
<%= @count %>

app/views/sites/impress.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @site.name %>
</p>
<p>
  <b>URL:</b>
  <%= @site.url %>
</p>
<p>
  <b>Description:</b>
  <%= @site.description %>
</p>
<p>
  <b>id:</b>
  <%= @site.id %>
</p>




<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>

app/views/sites/impress.js.erb
alert("Thanks for your vote!");

app/views/sites/index.html.erb
<div id="wrapper">
  <div id="topbar">
<img src="/assets/I_CARE_Logo.png" id="icare_logo"/>
      <span id="header_email"><span id="account_header">Account: </span><%= current_user.email %></span>
      <%= link_to image_tag('/assets/LogOut_BTN.png', :border => 0), destroy_user_session_path, :method => :delete, :id => 'signout_link' %>
      
  </div>

  <div id="manager_main_area">
    <div id="instructions">
      <div><img src="/assets/Reg_Title.png" id="register_header" /></div>
	<div id="manager_instructions">
	  One, enter a title and keywords that relate to a topic you want people to care about (Example: Polar Bears). 
	  <br/>Two, enter the URL where the button will be hosted<br/>
	  <i>*Check back for a full report reflecting your button(s) usage.</i>
	</div>
      
    </div>
    <table id="sites_table">
      <tr>
	<th>Care Topic</th>
	
	<th>Clicks to Date</th>
      </tr>

    <% @sites.each do |site| %>
	
      <tr>
	<td>
	    <%= form_for(site) do |f| %>
	    <div class="manager_caretopic_left">
		  <%= f.text_field :name, :class => 'name_box', :disabled => 'disabled' %><br/>
		  
		  <%= f.text_field :tags, :class => 'tags_box', :disabled => 'disabled' %><br/>
		  <%= f.text_field :url, :class => 'url_box', :disabled => 'disabled' %><br/>
		  <div class="register_button_rows">
		    <%= f.submit '' %>		  
		    <%= link_to image_tag('/assets/Edit_BTN.png', :border => 0), '#', :class => 'edit_btn' %>
		    <%= link_to image_tag('/assets/Remove_Active_BTN.png', :border => 0), site, confirm: 'Are you sure?', method: :delete %>
		    <%= link_to image_tag('/assets/HideCode_BTN.png', :class => 'hidecode_btn', :border => 0), '#'  %>
		    <%= link_to image_tag('/assets/SeeCode_BTN.png', :class => 'seecode_btn', :border => 0), '#'  %>
		  </div>
	    </div>
	  <div class="manager_caretopic_right">
	      <%= f.text_area :description, :class => 'description', :disabled => 'disabled' %>
	  </div>
	  <% end %>
	</td>
	
	<td class="clicks_to_date_column"> <%= site.votes_count  %><br/><br/><center><%= image_tag('/assets/FullReport_BTN.png', :class => 'full_report_btn', :border => 0) %></center></td>
      </tr>
      <tr class="showcode_row">
	<td colspan="2" >
	  <textarea class="manager_copytext" >
		<style> 
span#support_count1 { font-family: helvetica, arial, verdana; font-size: 11px; position: relative; bottom: 8px;} 
</style>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script> 
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script> 
<script  type="text/javascript" src='http://connect.facebook.net/en_US/all.js'></script> 
<script language="javascript">
		$(document).ready( function() {
			
			$.get('http://www.icare-movement.com/sites/get_count/4f843f41dbb2f57cfa00099e', function(data) {
			  $('span#support_count1').html(data);
			});
	        	$('a#icare_button_link').click( function() {
         		$.get($('a#icare_button_link').attr('href'), function(data) {
			
			}).error(function() { 
			      $(location).attr('http://www.icare-movement.com'); 
			});
			$( "#dialog:ui-dialog" ).dialog( "destroy" );
		    
			$( "#dialog-confirm" ).dialog({
				    resizable: false,
				    height: 290,
				    width: 488,
				    create: function(event, ui)
				    {
				       $(this).parents('.ui-dialog').css('background-image', "url('http://www.icare-movement.com/assets/SHARE_Overlay_03.png')");
				       $(this).parents('.ui-dialog').css('background-repeat', "no-repeat");
				       $(this).find('p').css('text-align', 'center');
				       $(this).parents().find('.ui-dialog-titlebar').css('display', 'none');
					   $(this).find('div#dialog-nav-options').css('margin', '65px 0 0 60px');
				      
				    }
				    ,
				    modal: true
				   
			    });    
			
			return false;
		      
		    });
		});
		
		</script> 
</script> <a id="icare_button_link" href="http://www.icare-movement.com/imp_sites/4f70b9b5dbb2f57cfa00000a/4f85f802dbb2f57cfa000e65" data-remote="true"><img src="http://www.icare-movement.com/ICARE_button_FINAL_03.png" border="0" /></a>  <span id="support_count4"></span>
<div id="dialog-confirm" style="display:none; ">
  <div class="ui-icon ui-icon-alert" style="position:relative; top:65px;margin-right:auto; text-align:center;">
    <img src="http://www.icare-movement.com/assets/SHARE_Overlay_Text.png" border="0" /></div>
  <a href="" id="exit_link" onclick="$('#dialog-confirm').dialog('close');" style="vertical-align:top; font-family:helvetica, arial, verdana; text-decoration: none; position: relative; top: -50px; left: 460px; font-size: 22px; color: #71a2a0; outline:none; width:19px; height:22px;"/><img src="http://www.ddb01.com/tony_s/icare_test_page/btn_x_close.jpg" border="0" /></a>
  <div id="dialog-nav-options" style="position: relative; top: 70px;">
    <div style="position: relative; left: -40px; "><a href="http://www.icare-movement.com" style="vertical-align:top; font-family:helvetica, arial, verdana; position: relative; font-size: 11px; color: #71a2a0;"/>Learn more at www.ICARE-MOVEMENT.com</a></div>
    <a href="http://www.icare-movement.com/sites/post_to_wall?name=testTopic%20A&description=testDescription%20A.%20Join%20the%20movement%20at%20www.ICARE-MOVEMENT.com"><img border="0" style="cursor:pointer;position: relative; left: 202px; bottom:25px; " src="http://www.icare-movement.com/assets/FB_SHARE_BTN.png" /></a></div>
</div>
	  </textarea>
	</td>
      </tr>
	
    <% end %>
      <tr id="new_topic_row">
	<td>
	    <%= form_for(@site) do |f| %>
		<div class="manager_caretopic_left" id="new_caretopic">
		     <%= f.text_field :name, :class => 'name_box', :value => 'Enter your title'  %><br/>
		 
		      <%= f.text_field :tags, :class => 'tags_box', :value => 'Keyword(s)'  %><br/>
		      <%= f.text_field :url, :class => 'url_box', :value => 'Enter your url' %><br/>
		      <%= f.submit '' %>		  
		      
				    
		</div>
		<div class="manager_caretopic_right">
		    <%= f.text_area :description, :class => 'description', :value => 'Enter your description' %>
		</div>
	  <% end %>
	</td>
	
	<td class="clicks_to_date_column"></td>
      </tr>
      <tr id="last_row">
	  <td>&nbsp;&nbsp;&nbsp;<%= link_to image_tag('/assets/AddTopic_BTN.png', :border => 0), '#', :id => 'add_topic_btn' %>
	  </td>
      </tr>
    </table>

    <br />
    <div>
      <a href="/api" style="color:#699">Click here for API information</a>
    </div>
     
  </div>

 

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/post_to_wall.html.erb
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>

<script language="javascript">

$(document).ready( function() {
  //  console.log("document.referer: " + document.referrer);
  //  console.log("name:  <%= CGI.escape(params[:name]) %>");
  //  console.log("redirect_uri: <%= request.host_with_port %>");
  //  console.log("description: <%= CGI.escape(params[:description]) %> ");
  //  console.log("caption: " + document.referrer.split('/')[2]);
    window.location.href = 'https://www.facebook.com/dialog/feed?app_id=363753320314028&display=page&link=' + document.referrer + '&picture=http://www.ddb01.com/tony_s/icare_test_page/fbshare.png&name=<%= CGI.escape(params[:name]) %>&caption=' + document.referrer.split('/')[2] +  '&description=<%= CGI.escape(params[:description]) %>&redirect_uri=http://<%= request.host %>/sites/return_to_referrer';
    

});
</script>

app/views/sites/show.html.erb
<style> span#support_count { font-family: helvetica, arial, verdana; font-size: 11px; position: relative; bottom: 8px;} </style>
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
		<script  type="text/javascript" src='http://connect.facebook.net/en_US/all.js'></script>
		<script language="javascript">
		$(document).ready( function() {
			$.get('http://<%= request.host_with_port  %>/sites/get_count/<%= @site.id %>', function(data) {
			  $('span#support_count').html(data);
			});
	        	$('a#icare_button_link').click( function() {
         		$.get($('a#icare_button_link').attr('href'), function(data) {
			
			}).error(function() { 
			      $(location).attr('http://<%= request.host_with_port  %>'); 
			});
			$( "#dialog:ui-dialog" ).dialog( "destroy" );
		    
			$( "#dialog-confirm" ).dialog({
				    resizable: false,
				    height: 290,
				    width: 488,
				    create: function(event, ui)
				    {
				       $(this).parents('.ui-dialog').css('background-image', "url('http://<%= request.host_with_port  %>/assets/SHARE_Overlay_03.png')");
				       $(this).parents('.ui-dialog').css('background-repeat', "no-repeat");
				       $(this).find('p').css('text-align', 'center');
				       $(this).parents().find('.ui-dialog-titlebar').css('display', 'none');
				       $(this).find('div#dialog-nav-options').css('margin-top', '65px');
				       $(this).find('div#dialog-nav-options').css('margin-left', '60px');

				   
				    }
				    ,
				    modal: true
				   
			    });    
			
			return false;
		      
		    });
		});
		
		</script> <a id="icare_button_link" href="http://<%= request.host_with_port  %>/imp_sites/<%= @current_user.id %>/<%= @site.id %>" data-remote="true"><img src="http://<%= request.host_with_port  %>/ICARE_button_FINAL_03.png" border="0" /></a> &nbsp;<span id="support_count"></span>
		
		<div id="dialog-confirm" style="display:none; ">
			<p><span class="ui-icon ui-icon-alert" style="margin-left: auto; margin-right: auto;"><br/><br/><br/><img src="http://<%= request.host_with_port  %>/assets/SHARE_Overlay_Text.png" /></span></p>
		<a href="" id="exit_link" onclick="$('#dialog-confirm').dialog('close');" style="vertical-align:top; font-family:helvetica, arial, verdana; text-decoration: none; position: relative; top: -120px; left: 460px; font-size: 22px; color: #71a2a0;"/>X</a>
			<div id="dialog-nav-options" style="position: relative; margin-top: 60px;"><div style="position: relative; left: -40px; "><a href="http://<%= request.host_with_port  %>" style="vertical-align:top; font-family:helvetica, arial, verdana; position: relative; top: 0px; margin-right: 17px; font-size: 11px; color: #71a2a0;"/>Learn more at www.ICARE-MOVEMENT.com</a></div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://<%= request.host_with_port  %>/sites/post_to_wall?name=<%= escape_javascript(URI::encode(@site.name.to_s)) %>&description=<%= escape_javascript(URI::encode(@site.description.to_s + '. Join the movement at www.ICARE-MOVEMENT.com')) %>"><img border="0" style="cursor:pointer;position: relative; left: 178px;margin-bottom: 17px; top: -25px;" src="http://<%= request.host.to_s  %>/assets/FB_SHARE_BTN.png" /></a></div>
		</div>